name: Deploy to EC2 Instances

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout: Descargar el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Guardar la clave SSH desde el secreto y ajustar permisos
    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > stalin.pem
        chmod 600 stalin.pem

    # 3. Conectar a la primera instancia y desplegar el archivo index.html
    - name: Deploy to first EC2 instance
      run: |
        ssh -o "StrictHostKeyChecking=no" -i "stalin.pem" ubuntu@ec2-52-54-210-132.compute-1.amazonaws.com "
          cd /var/www/html &&
          git pull origin main &&
          cp path/to/your/index.html /var/www/html/index.html &&
          sudo systemctl restart nginx
        "

    # 4. Conectar a la segunda instancia y desplegar el archivo index.html
    - name: Deploy to second EC2 instance
      run: |
        ssh -o "StrictHostKeyChecking=no" -i "stalin.pem" ubuntu@ec2-52-91-167-179.compute-1.amazonaws.com "
          cd /var/www/html &&
          git pull origin main &&
          cp path/to/your/index.html /var/www/html/index.html &&
          sudo systemctl restart nginx
        "
